/**
 * POST /api/decision/stream
 *
 * Body: { sessionId: string, optionId: string, participantWalletId: string,
 *         amountUsdc?: string }
 *
 * This is The Gaffer's actual money endpoint. The paid request is protected
 * by @x402/next's withX402 wrapper and settled by Circle Gateway batching.
 * Only the x402 resource-server after-settlement hook records the tap.
 *
 * Pipeline:
 *   1. Look up the session and the participant wallet in the in-memory
 *      registries; reject if either is missing or if the requested decision
 *      option is not part of the currently-open window.
 *   2. Build `PaymentRequirements` for Circle batching on Arc Testnet —
 *      payTo is the *session creator's* on-chain address; amount defaults
 *      to 0.0001 USDC (100 atomic units, the per-tap spec amount).
 *   3. Construct a `BatchEvmScheme` backed by `DcwBatchSigner`, which is
 *      our adapter that signs EIP-712 TransferWithAuthorization via Circle's
 *      `signTypedData` API instead of an in-process private key.
 *   4. `createPaymentPayload(...)` produces the signed payload, encoded as
 *      the PAYMENT-SIGNATURE header for the protected request.
 *   5. `withX402(...)` verifies and settles the payment through the Circle
 *      Gateway facilitator.
 *   6. Only the server's `onAfterSettle` hook calls `recordTap()`, which
 *      broadcasts the SSE `tap` event the UI listens for.
 *
 * Anti-fake notes:
 *   - There is NO branch that calls recordTap without a successful settle.
 *   - The returned PAYMENT-RESPONSE header is generated by the x402 wrapper
 *     and contains the actual Gateway settlement reference.
 *   - If anything in the pipeline throws (invalid signature, insufficient
 *     gateway balance, network) the caller sees the real error string from
 *     Circle, not a synthesized success.
 */
import { NextRequest, NextResponse } from 'next/server'
import { withX402 } from '@x402/next'
import { encodePaymentSignatureHeader, decodePaymentSignatureHeader } from '@x402/core/http'
import { x402ResourceServer, type FacilitatorClient } from '@x402/core/server'
import { BatchEvmScheme } from '@circle-fin/x402-batching/client'
import { GatewayEvmScheme } from '@circle-fin/x402-batching/server'
import { getAddress, parseUnits } from 'viem'
import type { Address } from 'viem'
import { getCachedSession, getSession } from '@/lib/session-store'
import { getParticipant } from '@/lib/participant-store'
import { recordTap } from '@/lib/decision-lifecycle'
import {
  ARC_TESTNET_NETWORK,
  CIRCLE_BATCHING_NAME,
  CIRCLE_BATCHING_VERSION,
  GATEWAY_AUTH_VALIDITY_WINDOW_SECONDS,
  TESTNET_GATEWAY_WALLET,
  buildBatchingPaymentRequirements,
  getBatchFacilitatorClient,
} from '@/lib/gateway'
import { DcwBatchSigner } from '@/lib/dcw-batch-signer'

export const dynamic = 'force-dynamic'

interface Body {
  sessionId?: string
  optionId?: string
  participantWalletId?: string
  amountUsdc?: string // decimal, default "0.0001"
  note?: string
}

const X402_VERSION = 2
const DEFAULT_TAP_USDC = '0.0001'

interface PreparedTap {
  sessionId: string
  optionId: string
  participantWalletId: string
  participantAddress: Address
  amountUsdc: string
  amountAtomic: string
  payTo: Address
  note?: string
}

const pendingTapsByNonce = new Map<string, PreparedTap>()

const x402Server = new x402ResourceServer(
  getBatchFacilitatorClient() as unknown as FacilitatorClient,
)
  .register(ARC_TESTNET_NETWORK, new GatewayEvmScheme())
  .onAfterSettle(async (context) => {
    const nonce = paymentNonce(context.paymentPayload)
    if (!nonce) return
    const pending = pendingTapsByNonce.get(nonce)
    if (!pending) return
    pendingTapsByNonce.delete(nonce)

    const session = await getSession(pending.sessionId)
    if (!session) return

    const amountFromSettlement = Number(
      BigInt(context.requirements.amount),
    ) / 1_000_000
    recordTap(session, {
      optionId: pending.optionId,
      amount: amountFromSettlement,
      note: pending.note,
      settlementTransaction: context.result.transaction,
      settlementNetwork: context.result.network,
      payer: context.result.payer,
    })
  })
  .onSettleFailure(async (context) => {
    console.error('[decision/stream] x402 settle failure', {
      nonce: paymentNonce(context.paymentPayload),
      message: context.error.message,
      requirements: context.requirements,
    })
    deletePendingTap(context.paymentPayload)
  })
  .onVerifiedPaymentCanceled(async (context) => {
    deletePendingTap(context.paymentPayload)
  })

const protectedStreamPost = withX402<unknown>(
  async (req: NextRequest) => {
    const body = await parseBody(req)
    const prepared = await (async () => {
      try {
        return await prepareTap(req, body)
      } catch (err) {
        if (err instanceof StreamRequestError) return err
        throw err
      }
    })()
    if (prepared instanceof StreamRequestError) {
      return NextResponse.json({ error: prepared.message }, { status: prepared.status })
    }
    const header = req.headers.get('payment-signature') || req.headers.get('x-payment')
    if (!header) {
      return NextResponse.json({ error: 'x402 payment header missing' }, { status: 402 })
    }
    const nonce = paymentNonceFromHeader(header)
    if (!nonce) {
      return NextResponse.json({ error: 'x402 payment nonce missing' }, { status: 400 })
    }
    pendingTapsByNonce.set(nonce, prepared)

    return NextResponse.json({
      sessionId: prepared.sessionId,
      optionId: prepared.optionId,
      amountUsdc: prepared.amountUsdc,
      amountAtomic: prepared.amountAtomic,
      participantWalletId: prepared.participantWalletId,
      payTo: prepared.payTo,
      x402: {
        verified: true,
        settlement: 'pending',
      },
    })
  },
  {
    accepts: {
      scheme: 'exact',
      price: (context) => `$${tapAmountFromContext(context)}`,
      network: ARC_TESTNET_NETWORK,
      payTo: (context) => payToFromContext(context),
      maxTimeoutSeconds: GATEWAY_AUTH_VALIDITY_WINDOW_SECONDS,
      extra: {
        name: CIRCLE_BATCHING_NAME,
        version: CIRCLE_BATCHING_VERSION,
        verifyingContract: getAddress(TESTNET_GATEWAY_WALLET),
      },
    },
    description: 'Stream one Gaffer supporter tap toward the selected option',
    mimeType: 'application/json',
    unpaidResponseBody: () => ({
      contentType: 'application/json',
      body: {
        error:
          'x402 payment required. Browser custodial wallets call this endpoint without X-Payment so the server can sign through Circle DCW and resubmit through withX402.',
      },
    }),
    settlementFailedResponseBody: (_context, settleResult) => ({
      contentType: 'application/json',
      body: {
        error: 'x402 settlement failed',
        reason: settleResult.errorReason ?? settleResult.errorMessage ?? 'unknown',
        details: settleResult.errorMessage ?? null,
        transaction: settleResult.transaction ?? null,
        network: settleResult.network ?? ARC_TESTNET_NETWORK,
      },
    }),
  },
  x402Server,
)

export async function POST(req: NextRequest): Promise<NextResponse> {
  let stage = 'parse'
  try {
    const incomingPayment =
      req.headers.get('payment-signature') || req.headers.get('x-payment')
    const body = await parseBody(req)
    const prepared = await prepareTap(req, body)
    if (incomingPayment) {
      return protectedStreamPost(
        buildInternalX402Request(req, body, prepared, incomingPayment),
      )
    }

    stage = 'build-requirements'
    const requirements = buildBatchingPaymentRequirements({
      payTo: prepared.payTo,
      amountAtomic: prepared.amountAtomic,
    })

    stage = 'sign-payload'
    const signer = new DcwBatchSigner(
      prepared.participantWalletId,
      prepared.participantAddress,
    )
    const scheme = new BatchEvmScheme(signer)
    const signed = await scheme.createPaymentPayload(
      X402_VERSION,
      requirements,
    )

    stage = 'x402-protected-submit'
    const signedWithAccepted = {
      ...signed,
      resource: {
        url: new URL(req.url).pathname,
        description: 'Stream one Gaffer supporter tap toward the selected option',
        mimeType: 'application/json',
      },
      accepted: requirements,
    }
    const paymentHeader = encodePaymentSignatureHeader(
      signedWithAccepted as unknown as Parameters<typeof encodePaymentSignatureHeader>[0],
    )
    return protectedStreamPost(
      buildInternalX402Request(req, body, prepared, paymentHeader),
    )
  } catch (err: unknown) {
    const anyErr = err as {
      message?: string
      code?: string | number
      status?: number
      response?: { status?: number; data?: unknown }
    }
    const info = {
      stage,
      message: anyErr.message ?? String(err),
      details: {
        code: anyErr.code ?? null,
        status: anyErr.status ?? anyErr.response?.status ?? null,
        responseData: anyErr.response?.data ?? null,
      },
    }
    console.error('[decision/stream] failed at stage', stage, info)
    return NextResponse.json(info, {
      status: err instanceof StreamRequestError ? err.status : 500,
    })
  }
}

async function parseBody(req: Request): Promise<Body> {
  return (await req.json().catch(() => ({}))) as Body
}

async function prepareTap(req: NextRequest, body: Body): Promise<PreparedTap> {
  const querySessionId = req.nextUrl.searchParams.get('sessionId')
  const queryAmountUsdc = req.nextUrl.searchParams.get('amountUsdc')
  if (!body.sessionId || !body.optionId || !body.participantWalletId) {
    throw new StreamRequestError(
      400,
      'sessionId, optionId and participantWalletId are required',
    )
  }
  if (querySessionId && querySessionId !== body.sessionId) {
    throw new StreamRequestError(400, 'query sessionId does not match body sessionId')
  }

  const amountUsdc = body.amountUsdc ?? queryAmountUsdc ?? DEFAULT_TAP_USDC
  const amountAtomic = parseUnits(amountUsdc, 6).toString()
  if (queryAmountUsdc && parseUnits(queryAmountUsdc, 6).toString() !== amountAtomic) {
    throw new StreamRequestError(400, 'query amountUsdc does not match body amountUsdc')
  }

  const session = await getSession(body.sessionId)
  if (!session) {
    throw new StreamRequestError(404, 'session not found')
  }
  const decision = session.matchState.currentDecision
  if (!decision || !decision.isOpen) {
    throw new StreamRequestError(409, 'no open decision window for this session')
  }
  if (!decision.options.some((o) => o.id === body.optionId)) {
    throw new StreamRequestError(
      400,
      'optionId is not part of the current decision window',
    )
  }
  const participant = getParticipant(session.id, body.participantWalletId)
  if (!participant) {
    throw new StreamRequestError(
      404,
      'participant wallet not registered for this session — call /api/wallet/participant first',
    )
  }

  if (
    getAddress(participant.address) ===
    getAddress(session.matchState.creatorAddress as Address)
  ) {
    throw new StreamRequestError(
      409,
      'This is the creator wallet for this room. Open the session link with a different reader account to settle a real paid steer.',
    )
  }

  return {
    sessionId: session.id,
    optionId: body.optionId,
    participantWalletId: participant.walletId,
    participantAddress: participant.address,
    amountUsdc,
    amountAtomic,
    payTo: session.matchState.creatorAddress as Address,
    note: body.note?.trim() || undefined,
  }
}

function buildInternalX402Request(
  req: NextRequest,
  body: Body,
  prepared: PreparedTap,
  paymentHeader: string,
): NextRequest {
  const url = new URL(req.url)
  url.searchParams.set('sessionId', prepared.sessionId)
  url.searchParams.set('amountUsdc', prepared.amountUsdc)

  const headers = new Headers(req.headers)
  headers.set('content-type', 'application/json')
  headers.set('payment-signature', paymentHeader)
  headers.delete('x-payment')
  headers.delete('content-length')

  return new NextRequest(url.toString(), {
    method: 'POST',
    headers,
    body: JSON.stringify({ ...body, amountUsdc: prepared.amountUsdc }),
  })
}

function tapAmountFromContext(context: {
  adapter: { getQueryParam?: (name: string) => string | string[] | undefined }
}): string {
  const raw = context.adapter.getQueryParam?.('amountUsdc')
  const amount = Array.isArray(raw) ? raw[0] : raw
  return amount || DEFAULT_TAP_USDC
}

function payToFromContext(context: {
  adapter: { getQueryParam?: (name: string) => string | string[] | undefined }
}): string {
  const raw = context.adapter.getQueryParam?.('sessionId')
  const sessionId = Array.isArray(raw) ? raw[0] : raw
  if (!sessionId) return '0x0000000000000000000000000000000000000000'
  const session = getCachedSession(sessionId)
  return session?.matchState.creatorAddress ?? '0x0000000000000000000000000000000000000000'
}

function paymentNonceFromHeader(header: string): string | null {
  try {
    return paymentNonce(decodePaymentSignatureHeader(header))
  } catch {
    return null
  }
}

function paymentNonce(paymentPayload: unknown): string | null {
  const payload = paymentPayload as {
    payload?: { authorization?: { nonce?: unknown } }
  }
  const nonce = payload.payload?.authorization?.nonce
  return typeof nonce === 'string' ? nonce.toLowerCase() : null
}

function deletePendingTap(paymentPayload: unknown): void {
  const nonce = paymentNonce(paymentPayload)
  if (nonce) pendingTapsByNonce.delete(nonce)
}

class StreamRequestError extends Error {
  constructor(
    readonly status: number,
    message: string,
  ) {
    super(message)
  }
}
